name: CI - Train models

on:
  push:
    branches: [ kernelridge ]

jobs:
  run-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "assignment _1/requirements.txt"

      - name: Run DecisionTree training
        run: |
          python "assignment _1/train.py"

      - name: Run KernelRidge training
        run: |
          python "assignment _1/train2.py"
